### ISSUE TITLE
Improve the visibility of 'Use Default Title ' in Dark Mode 

### ISSUE THREAD

**Issue by nisha-laur** [SnowScriptWinterOfCode/Notes-App#55] opened 2024-01-04 10:16 UTC
Light Mode :
<img width="334" alt="image" src="https://github.com/SnowScriptWinterOfCode/Notes-App/assets/104618576/b0938899-73ba-4298-acd2-e66453dcb4ea">
Dark Mode :
<img width="260" alt="image" src="https://github.com/SnowScriptWinterOfCode/Notes-App/assets/104618576/bd10b449-0abb-4901-939e-45d59b718d03">

**Comment by jhakrishan20** [comment] 2024-01-04 13:13
Hey @nisha-laur please assign me this issue

**Comment by AarnaSinghal** [comment] 2024-01-04 14:08
pls assign this issue

**Comment by nisha-laur** [comment] 2024-01-04 14:56
Since @jhakrishan20 asked for it first , it definitely goes to him .

**Comment by jhakrishan20** [comment] 2024-01-05 10:28
@nisha-laur  Thank you for assigning.

**Comment by jhakrishan20** [comment] 2024-01-05 13:26
Hey @nisha-laur  , the issue is resolved and the  PR #63 is submitted my me , thank you .

**Closed as completed** 2024-01-06 09:53 UTC
